WTF_CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = 'user@gmail.com'
MAIL_PASSWORD = 'password'
ADMINS =['user@gmail.com']